version: '3.8'
services:
  monitor:
    build:
      context: ./code
      dockerfile: Dockerfile.monitor
    container_name: hormuznet_monitor
    network_mode: host
    command:
    - -brokers=192.168.10.127:6008
    - -porta=8085
    restart: on-failure
