version: '3.8'

services:
  broker1:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker1
    command: ["-id=B1","-setor=Setor_Noroeste","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6000","-vizinhos=broker2:6001,broker8:6007,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker2:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker2
    command: ["-id=B2","-setor=Setor_Norte","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6001","-vizinhos=broker1:6000,broker3:6002,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker3:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker3
    command: ["-id=B3","-setor=Setor_Nordeste","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6002","-vizinhos=broker2:6001,broker4:6003,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker4:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker4
    command: ["-id=B4","-setor=Setor_Leste","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6003","-vizinhos=broker3:6002,broker5:6004,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker5:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker5
    command: ["-id=B5","-setor=Setor_Sudeste","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6004","-vizinhos=broker4:6003,broker6:6005,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker6:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker6
    command: ["-id=B6","-setor=Setor_Sul","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6005","-vizinhos=broker5:6004,broker7:6006,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker7:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker7
    command: ["-id=B7","-setor=Setor_Sudoeste","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6006","-vizinhos=broker6:6005,broker8:6007,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker8:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker8
    command: ["-id=B8","-setor=Setor_Oeste","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6007","-vizinhos=broker7:6006,broker1:6000,broker9:6008"]
    networks:
      - hormuznet
    restart: on-failure

  broker9:
    build:
      context: ./code
      dockerfile: Dockerfile.broker
    container_name: hormuznet_broker9
    command: ["-id=B9","-setor=Setor_Centro","-udp=224.0.0.1:8080","-tcp=0.0.0.0:6008","-vizinhos=broker1:6000,broker3:6002,broker5:6004,broker7:6006"]
    networks:
      - hormuznet
    restart: on-failure

  drone1:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_nw_1
    command: ["-id=Drone_NW_1","-brokers=broker1:6000,broker8:6007","-x=250","-y=250"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  drone2:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_n_1
    command: ["-id=Drone_N_1","-brokers=broker2:6001,broker3:6002","-x=500","-y=250"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  drone3:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_ne_1
    command: ["-id=Drone_NE_1","-brokers=broker3:6002,broker4:6003","-x=750","-y=250"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  drone4:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_e_1
    command: ["-id=Drone_E_1","-brokers=broker4:6003,broker5:6004","-x=750","-y=500"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  drone5:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_sw_1
    command: ["-id=Drone_SW_1","-brokers=broker7:6006,broker6:6005","-x=250","-y=750"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  drone6:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_se_1
    command: ["-id=Drone_SE_1","-brokers=broker5:6004,broker6:6005","-x=750","-y=750"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  drone7:
    build:
      context: ./code
      dockerfile: Dockerfile.drone
    container_name: hormuznet_drone_c_1
    command: ["-id=Drone_C_1","-brokers=broker9:6008,broker1:6000","-x=500","-y=500"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8
      - broker9

  monitor:
    build:
      context: ./code
      dockerfile: Dockerfile.monitor
    container_name: hormuznet_monitor
    command: ["-brokers=broker1:6000,broker2:6001,broker3:6002,broker4:6003,broker5:6004,broker6:6005,broker7:6006,broker8:6007,broker9:6008", "-porta=8082"]
    ports:
      - "8082:8082"
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1
      - broker2
      - broker3
      - broker4
      - broker5
      - broker6
      - broker7
      - broker8

  sensor_1:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_nw_1
    command: ["-id=boia_nw_1","-tipo=boia","-setor=Setor_Noroeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=209", "-y=107"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_2:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_nw_2
    command: ["-id=boia_nw_2","-tipo=boia","-setor=Setor_Noroeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=244", "-y=127"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_3:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_meteo_nw_3
    command: ["-id=meteo_nw_3","-tipo=meteo","-setor=Setor_Noroeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=233", "-y=222"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_4:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_n_1
    command: ["-id=boia_n_1","-tipo=boia","-setor=Setor_Norte","-broker=224.0.0.1:8080","-intervalo=15000", "-x=499", "-y=257"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_5:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_n_2
    command: ["-id=visual_n_2","-tipo=visual","-setor=Setor_Norte","-broker=224.0.0.1:8080","-intervalo=15000", "-x=420", "-y=255"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_6:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_n_3
    command: ["-id=boia_n_3","-tipo=boia","-setor=Setor_Norte","-broker=224.0.0.1:8080","-intervalo=15000", "-x=428", "-y=282"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_7:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_ne_1
    command: ["-id=visual_ne_1","-tipo=visual","-setor=Setor_Nordeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=898", "-y=205"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_8:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_sonar_ne_2
    command: ["-id=sonar_ne_2","-tipo=sonar","-setor=Setor_Nordeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=873", "-y=222"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_9:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_meteo_ne_3
    command: ["-id=meteo_ne_3","-tipo=meteo","-setor=Setor_Nordeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=811", "-y=243"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_10:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_e_1
    command: ["-id=boia_e_1","-tipo=boia","-setor=Setor_Leste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=724", "-y=513"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_11:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_radar_e_2
    command: ["-id=radar_e_2","-tipo=radar","-setor=Setor_Leste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=789", "-y=463"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_12:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_e_3
    command: ["-id=visual_e_3","-tipo=visual","-setor=Setor_Leste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=714", "-y=435"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_13:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_radar_se_1
    command: ["-id=radar_se_1","-tipo=radar","-setor=Setor_Sudeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=715", "-y=724"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_14:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_radar_se_2
    command: ["-id=radar_se_2","-tipo=radar","-setor=Setor_Sudeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=894", "-y=884"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_15:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_radar_se_3
    command: ["-id=radar_se_3","-tipo=radar","-setor=Setor_Sudeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=884", "-y=777"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_16:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_s_1
    command: ["-id=visual_s_1","-tipo=visual","-setor=Setor_Sul","-broker=224.0.0.1:8080","-intervalo=15000", "-x=452", "-y=765"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_17:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_s_2
    command: ["-id=boia_s_2","-tipo=boia","-setor=Setor_Sul","-broker=224.0.0.1:8080","-intervalo=15000", "-x=462", "-y=775"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_18:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_radar_s_3
    command: ["-id=radar_s_3","-tipo=radar","-setor=Setor_Sul","-broker=224.0.0.1:8080","-intervalo=15000", "-x=481", "-y=780"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_19:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_radar_sw_1
    command: ["-id=radar_sw_1","-tipo=radar","-setor=Setor_Sudoeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=280", "-y=863"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_20:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_sonar_sw_2
    command: ["-id=sonar_sw_2","-tipo=sonar","-setor=Setor_Sudoeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=111", "-y=766"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_21:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_sw_3
    command: ["-id=visual_sw_3","-tipo=visual","-setor=Setor_Sudoeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=299", "-y=817"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_22:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_meteo_w_1
    command: ["-id=meteo_w_1","-tipo=meteo","-setor=Setor_Oeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=128", "-y=598"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_23:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_boia_w_2
    command: ["-id=boia_w_2","-tipo=boia","-setor=Setor_Oeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=160", "-y=568"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_24:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_w_3
    command: ["-id=visual_w_3","-tipo=visual","-setor=Setor_Oeste","-broker=224.0.0.1:8080","-intervalo=15000", "-x=173", "-y=400"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_25:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_c_1
    command: ["-id=visual_c_1","-tipo=visual","-setor=Setor_Centro","-broker=224.0.0.1:8080","-intervalo=15000", "-x=527", "-y=468"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_26:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_visual_c_2
    command: ["-id=visual_c_2","-tipo=visual","-setor=Setor_Centro","-broker=224.0.0.1:8080","-intervalo=15000", "-x=526", "-y=486"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

  sensor_27:
    build:
      context: ./code
      dockerfile: Dockerfile.sensor
    container_name: hormuznet_sonar_c_3
    command: ["-id=sonar_c_3","-tipo=sonar","-setor=Setor_Centro","-broker=224.0.0.1:8080","-intervalo=15000", "-x=450", "-y=423"]
    networks:
      - hormuznet
    restart: on-failure
    depends_on:
      - broker1

networks:
  hormuznet:
    name: hormuznet
    driver: bridge
