FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o monitor_exec ./cmd/monitor/

FROM scratch
COPY --from=builder /app/monitor_exec /monitor_exec
COPY --from=builder /app/assets /assets
ENTRYPOINT ["/monitor_exec"]
