FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o sensor_exec ./cmd/sensor/

FROM scratch
COPY --from=builder /app/sensor_exec /sensor_exec
ENTRYPOINT ["/sensor_exec"]
